name: Run Tests
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Run Your Script
        run: |
          python scripts.py  # Replace with the command to run your script
